<div class="center subscribe hidden"><input type="checkbox" id="iWill-news" checked="">&nbsp;&nbsp;
    <label for="iWill-news">Я подписываюсь на рассылку новостей</label>
</div>
<div class="center subscribe">
    <input type="checkbox" id="iWill-1">&nbsp;&nbsp;
    <label for="iWill-1">Я даю</label> &nbsp;
    <span class="read-iWill-text" data-oferta="oferta-obrabotka-pd">согласие на обработку моих персональных данных</span><br>
    <label>и принимаю условия</label> &nbsp;
    <span class="read-iWill-text" data-oferta="oferta-polzovatelskoe-soglashenie">пользовательского соглашения</span>
    &nbsp;и &nbsp;<span class="read-iWill-text" data-oferta="oferta-politika-konfidencialnosti">политики конфиденциальности</span>
</div>
<div class="center subscribe hidden">
    <input type="checkbox" id="iWill-account" data-email="">&nbsp;&nbsp;
    <label for="iWill-account">Создать учетную запись с данными первого пассажира</label>
</div>
<div class="center">
    <a id="done" class="custom-button submit" type="button" href="#" disabled="">
        <span data-hover="Все верно">Готово</span>
    </a>
</div>
