<div id="help" style="display: none;">
    <div class="button close"><i class="fa fa-angle-down"></i></div>
    <ol>
        <br>
        <h4>Как оформить билет?</h4>
        <br>
        <li>
            Перед оформлением внимательно ознакомьтесь с предоставленной информацией о поездке!
        </li>
        <li>Убедитесь, что дата, время, остановки посадки и высадки Вас устраивают и Вы готовы оформить занятие мест в автобусе.</li>
        <li>
            Отметьте понравившиеся свободные места в автобусе. <br>
            Разметка мест:
            <span class="empty-place-color">Свободно</span>
            <span class="reserved-place-color">Место забронировано</span>
            <span class="self-reserved-color">Зарезервировано Вами на 5 мин.</span>
            <span class="reserved-color">Зарезервировано за кем-то на 5 мин.</span>
        </li>
        <li>
            Укажите Ваши телефон и адрес электронной почты.
            Телефон нужен для экстренной связи с Вами.
        </li>
        <li>
            Введите информацию о пассажире. <br>
            Вы можете добавить или удалить пассажиров, нажимая кнопки <i class="fa fa-plus" style="color:green;"></i> и <i class="fa fa-close" style="color:red;"></i>,<br>
            а также нажимая на места на схеме автобуса.
        </li>
        <li>
            Когда все будет готово, нажмите кнопку <span style="color:green;">"Готово"</span>. <br>
        </li>
        <i class="fa fa-smile-o" aria-hidden="true"></i>&nbsp; Приятных покупок и спасибо, что Вы с нами!
    </ol>
</div>
