<div id="bus" class="col-xs-12 col-md-4">
    <input id="hidd-reis-id" type="hidden" value="<?= $this->reisId?>">
    <input id="hidd-bus-size" type="hidden" value="<?= $this->busSize?>">
    <input id="hidd-bus-conf" type="hidden" value='<?= json_encode(json_encode($this->busConfig))?>'>
</div>
<!--  --><?//  $this->bus()->setItems($this->reis->getPaxes());?>
<!--  --><?//= $this->bus()->render();?>