    <td class="center">
        <span class="mobile-only">Пассажир <span class="pax-counter">1</span> &nbsp;
            <span class="text-muted mobile-label">Номер места:</span>
        </span><br class="mobile-only">
        <div>
            <input name="place-number" class="form-control place-number" type="text" value="" placeholder="" readonly="" title="Нажмите на это поле и выберите места на схеме">
            <span class="mobile-only text-muted small" style="width:calc( 100% - 50px )">Нажмите на это поле и выберите места на схеме</span>
        </div>
    </td>
    <td class="mobile-only">Фамилия:</td>
    <td class="w110">
        <input id="f-0" name="f" class="form-control icon-close error" type="text" placeholder="Фамилия">
        <span class="icon"></span>
    </td>
    <td class="mobile-only">Имя:</td>
    <td class="w110">
        <input id="i-0" name="i" class="form-control icon-close error" type="text" placeholder="Имя">
        <span class="icon"></span>
    </td>
    <td class="mobile-only">Отчество:</td>
    <td class="w110">
        <input id="o-0" name="o" class="form-control icon-close error" type="text" placeholder="Отчество">
        <span class="icon"></span>
    </td>
    <td class="mobile-only">Пол:</td>
    <td class="w50">
        <select name="sex" class="form-control">
            <option value="0">Ж</option>
            <option value="1">М</option>
        </select></td>
    <td class="mobile-only">Дата рождения:</td>
    <td class="w100">
        <input id="dr-0" name="dr" class="form-control icon-close error" type="text" mask="00.00.0000" placeholder="дд.мм.гггг" maxlength="10">
        <span class="icon"></span>
    </td>
    <td class="mobile-only">Гражданство:</td>
    <td class="w100">
        <input id="gr-0" name="grazhd" class="form-control icon-close ui-autocomplete-input" type="text" data-id="643" value="Россия" placeholder="Страна" autocomplete="off">
        <span class="icon"></span>
    </td>
    <td class="mobile-only">Удостоверение личности:</td>
    <td class="w100">
        <input id="dt-0" name="doc" class="form-control icon-close ui-autocomplete-input" type="text" data-id="0" value="Паспорт" placeholder="Удостоверение личности" autocomplete="off">
        <span class="icon"></span>
    </td>
    <td class="mobile-only">Серия и номер удостоверения:</td>
    <td class="mobile-only">
        <div class="info docnumhelp text-muted">Формат номера документа: 4+6 цифр Пример: 2002 123456</div>
    </td>
    <td class="w120">
        <input id="dn-0" name="docnum" class="form-control icon-close error" type="text" mask="0000 000000" placeholder="0000 000000" maxlength="11">
        <span class="icon"></span>
    </td>
    <td class="buttons-container">
        <div class="button trash" title="Удалить пассажира">
            <span class="mobile-only"> Удалить пассажира </span>
            <i class="fa fa-close"></i></div>
        <div class="button info docnumhelp non-mobile-only" title="Формат номера документа: 4+6 цифр Пример: 2002 123456">
            <i class="fa fa-info"></i>
        </div>
        <div class="button add mobile-only">
            <span> Добавить пассажира </span>
            <i class="fa fa-plus"></i>
        </div>
    </td>
