<table class="table condensed costs_and_tarifs">
    <thead>
    <tr>
        <td colspan="11"><h4>Тарифы и цены</h4></td>
    </tr>
    </thead>
    <thead>
    <tr>
        <th class="non-mobile-only">Тариф</th>
        <th class="non-mobile-only">Цена по тарифу</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td class="w120">Полный, 100%</td>
        <td class="w120" data-name="Полный:100%">1000 <i class="fa fa-icon fa-ruble"></i></td>
    </tr>
    </tbody>
</table>