<? $lastKey = (count($this->tracePoints) - 1) ?>
<? foreach ($this->tracePoints as $key => $point): ?>
    <? $p = explode(":", $point["data"]) ?>
    <div class="path-point">
        <div>
            <span class="point-time" style="cursor: pointer;"><?= $point["time_point"]; ?></span>
            <span class="point-date" style="cursor: pointer;">
                <?= ($key == 0) ? $point["date_point"] : ""; ?>
                <?= ($key == $lastKey) ? $point["date_point"] : ""; ?>
            </span>
        </div>
        <div>
            <? if (($key == 0) || ($key == $lastKey)): ?>
                <input name="point-checkbox"
                       type="checkbox"
                       checked="checked"
                       class="check-point"
                       data-id="<?= $this->escapeHtml($p[2])?>"
                       data-cid="<?= $this->escapeHtml($p[0])?>"
                       data-points="<?= $this->escapeHtml($point["data"])?>"
                       data-points-txt="<?= $this->escapeHtml($p[1])?>, <?= $this->escapeHtml($p[3])?>"
                       data-from-city="<?= $this->escapeHtml($p[1])?>"
                       data-from-point="<?= $this->escapeHtml($p[3])?>"
                       style="display: inline-block;" disabled="">
                <span class="city selected-point" style="cursor: pointer;"><?= $this->escapeHtml($p[1])?></span>
                <span class="point selected-point" style="cursor: pointer;"><?= $this->escapeHtml($p[3])?></span>
            <?php else: ?>
                <span class="city" style="cursor: pointer;"><?= $this->escapeHtml($p[1])?></span>
                <span class="point" style="cursor: pointer;"><?= $this->escapeHtml($p[3])?></span>
            <?php endif; ?>
        </div>
    </div>
<? endforeach; ?>
