<?php
$title = "Заказ билета на автобус";
$this->headTitle($title);
$this->publicMenu()->setActiveItemId("home");
$this->publicMenu()->setBreadCrumbs("", "Заказ билета");
/*$this->inlineScript()->appendFile($this->basePath("/js/jquery.mask.js" . "?" . random_int(11111, 99999)));*/
$this->headLink()->appendStylesheet($this->basePath("css/w/bus-view-pub.css" . "?" . random_int(11111, 99999)));
$this->headLink()->appendStylesheet($this->basePath("css/front/pay.css" . "?" . random_int(11111, 99999)));


$this->inlineScript()->appendFile($this->basePath("js/phone-mask.js" . "?" . random_int(11111, 99999)));
$this->inlineScript()->appendFile($this->basePath('js/w/bus-view.js'.'?'.random_int(11111, 99999)));
$this->inlineScript()->appendFile($this->basePath('js/front/bus-places.js'.'?'.random_int(11111, 99999)));
$this->inlineScript()->appendFile($this->basePath( $this->basePath("js/front/zakaz.js"."?".random_int(11111, 99999)) ))
?>

<section class="shop-checkout">
    <div class="container">
        <h3><?= $title ?></h3>
        <?=$this->partial("_how_get_ticket");?>
        <div class="row" id="form">
            <div class="col-xs-12">
                <table class="table search-result-table">
                    <thead></thead>
                    <tbody class="active" style="opacity:1" data-id="4798">
                        <tr>
                            <?=$this->partial("_reis_info", [
                                "reisParams" => $this->reis->getParams(),
                                "titleShort" => $this->usr["data"]["profile"]["org"]["title_short"],
                                "nameFrom" => $this->reis->getNameFrom(),
                                "nameTo" => $this->reis->getNameTo(),
                                "bus" => $this->bus
                            ]);?>
                        </tr>
                        <tr class="reis-detail common-data">
                            <td colspan="3">
                                <div id="bus-stops" class="col-xs-12 col-md-5" style="padding-left:0;">
                                    <h4 style="margin:10px 3px !important;">Остановки </h4>
                                    <div class="col-xs-12 reis-detail-left">
                                        <div class="path-line"></div>
                                        <?=$this->partial("_trace_points", ["tracePoints" => $this->points]);?>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-md-7 reis-detail-right">
                                    <?=$this->partial("_pass_bus", [
                                        "reisId"    => $this->reis->getId(),
                                        "busSize"   => $this->bus->getSize(),
                                        "busConfig" => $this->bus->getConfig(),
                                    ]);?>
                                    <div class="col-xs-12 col-md-8 costs_and_tarifs">
                                    <!--  --><?//=$this->partial('_tariffs_prices');?>
                                        <table class="table condensed contacts" style="">
                                            <thead>
                                                <tr>
                                                    <td colspan="11"><h4>Ваши контакты</h4></td>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td class="w120">E-mail:</td>
                                                    <td class="w120">
                                                        <input id="email" class="form-control icon-close error" type="text" placeholder="email@site.ru">
                                                        <span class="icon"></span>
                                                    </td>

                                                </tr>
                                                <tr>
                                                    <td class="w120">Телефон:</td>
                                                    <td class="w120">
                                                        <input id="phone" class="form-control icon-close error" type="text" placeholder="7-000-000-00-00" title="Варианты: 7-800-375-22-22, 373-555-787-55, 375-555-588-222, 996-555-788-555, 8-800-375-22-22" maxlength="15" autocomplete="off">
                                                        <span class="icon"></span>
                                                    </td>

                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        <tr class="reis-detail paxes" id="paxes">
                            <td colspan="3">
                                <table class="table condensed">
                                    <thead>
                                        <tr>
                                            <td colspan="10"><h4>Пассажиры</h4></td>
                                            <td colspan="2" class="buttons-container non-mobile-only">
                                                <div class="button add passenger">
                                                    <span> Добавить пассажира </span>
                                                    <i class="fa fa-plus"></i>
                                                </div>
                                            </td>
                                        </tr>
                                    </thead>
                                    <thead class="non-mobile-only">
                                        <?=$this->partial("_pass_head");?>
                                    </thead>
                                    <tbody class="pass_row">
                                        <tr style="border-bottom: 1px solid rgb(52, 52, 52);">
                                            <?=$this->partial("_pass_add");?>
                                        </tr>
                                    </tbody>
                                    <!--  --><?//  $this->passengers()->setItems($this->reis->getPaxes());?>
                                    <!--  --><?//= $this->passengers()->render();?>
                                </table>
                                <?=$this->partial("_agreement");?>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row" id="welcomina" style="display:none;">
            <div class="col-xs-12">
                <table class="table" style="background:none;">
                    <tfoot>
                    <tr>
                        <th>
                            <p class="center"><i class="fa fa-smile-o" aria-hidden="true"></i>&nbsp; Спасибо Вам за то, что Вы используете Гоубас!</p>
                            <div class="center">
                                <a href="<?= $this->url('home'); ?>" class="custom-button">
                                    <span data-hover="Начало...">Начало</span>
                                </a>
                            </div>
                        </th>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</section>
