<?php
$title = "Заказ билета на автобус";
$this->headTitle($title);
$this->publicMenu()->setActiveItemId('home');
$this->publicMenu()->setBreadCrumbs('', 'Список билетов');

?>

<section class="shop-checkout">
    <div class="container">
        <h3>&nbsp;<?=$title?></h3>

        <div class="row" id="form">
            <div class="col-xs-12">
                <table class="table search-result-table">
                    <tfoot>
                        <tr>
                            <th>
                                <h4>Время действия ссылки истекло!</h4>
                            </th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>

    </div>
</section>
