<?php
$this->headTitle('Вход в систему');
$this->publicMenu()->setActiveItemId('login');
$this->publicMenu()->setBreadCrumbs('home,login');

$this->headLink()
        ->appendStylesheet($this->basePath('css/front/login.css'.'?'.random_int(11111, 99999)))
    ;    

$form->setAttribute('class', 'custom-form');

$form->get('login')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Логин, e-mail или телефон',
    'required' => true,
    'autofocus' => false
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);

$form->get('password')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Пароль',
    'required' => true,
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);

$form->get('remember_me')->setAttributes([
    'style'=>'float:left;height:auto;margin:5px 15px 0 0;', 
    ]);

$form->get('submit')->setAttributes([
    'class'=>'custom-button center-block',
    'value'=>'Вход'    
]);

$form->prepare();
?>

<section class="terms">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
		<div class="form-container">
                    <!-- Main Heading Starts -->
                    <div class="text-center top-text">
                        <h1><span>вход</span> пользователя</h1>
                        <p>приятно снова видеть Вас!</p>
                    </div>
                    <!-- Main Heading Ends -->

                    <!-- Form Starts -->
                    
                        <?php if ($isLoginError): ?>
                            <div class="col-sm-2"></div>
                            <div class="col-sm-8 text-center my_message visible">
                                <div class="output_message info left">
                                    <h4 class=head>Если Вы видите это сообщение значит </h4>
                                    1. Вы указали неверные логин, почту, телефон или пароль!<br>
                                    2. Вы не прошли проверку защиты от роботов!<br>
                                    3. Логин и пароль верные, учетная запись активирована Вами по ссылке из письма, но пока не активирована администратором!            
                                </div>
                            </div>
                            <div class="col-sm-2"></div>
                        <?php endif; ?>

                        <?= $this->form()->openTag($form); ?>

                    
                        <div class="row">
                        <div class="col-md-4">&nbsp;</div>
                        <div class="col-md-4">
                            
                            <div class="form-group">
                                <?= $this->formLabel($form->get('login')); ?>
                                <?= $this->formElement($form->get('login')); ?>
                            </div>
                            
                            <div class="form-group">
                                <?= $this->formLabel($form->get('password')); ?>
                                <?= $this->formElement($form->get('password')); ?>
                            </div>
                        <div class="col-md-4">&nbsp;</div>
                        </div>
                        </div>
            
                        <div class="row">
                        <div class="col-md-4">&nbsp;</div>
                        <div class="form-group col-md-4">
                            <?= $this->formElement($form->get('remember_me')); ?> 
                            <label style="float:left;max-width:50%;">Запомнить меня</label>                        
                            <label style="float:right"><a href="<?= $this->url('reset-password') ?>">Забыли пароль?</a></label>

                        </div>
                        <div class="col-md-4">&nbsp;</div>
                        </div>
                    
                    <div class="row">
                    <div class="col-md-4">&nbsp;</div>
                    <div class="form-group col-md-4">
                        <div style="padding-left: calc( (100% - 300px) / 2 );">
                        <?= $this->formElement($form->get('captcha')); ?>
                        <ul><li class="form-error-msg"><b><?= Application\Filter\LatToRus::get( $this->formElementErrors($form->get('captcha'))); ?></b></li></ul>                        
                        </div>
                    </div>
                    <div class="col-md-4">&nbsp;</div>
                    </div>
                            
                        <?= $this->formElement($form->get('redirect_url')); ?>
                        <?= $this->formElement($form->get('csrf')) ?>
            
            <?= $this->formElement($form->get('submit')); ?>
            <!--button class="btn btn-lg btn-primary btn-block" type="submit">Войти</button-->
        <?= $this->form()->closeTag(); ?>
    </div>
</div>

                </div>
	    </div>
	</div>
    </div>
</section>

    <?php
    $this->inlineScript()->captureStart();
    echo <<<JS
$(function () {
    if(isMobile()){
        $("div.form-container").html(
            '<div class="col-sm-12 text-center my_message visible">'+
            '    <div class="output_message info left">'+
            '        <h4 class=head>Ограничение!</h4>'+
            '        Вы пытаетесь войти в систему с мобильного устройства!<br><br>'+
            '        Система расчитана только для использования в десктопном режиме!<br><br>'+
            '        Для работы войдите в систему при помощи ноутбука или персонального компьютера!'+
            '    </div>'+
            '</div>');
    };
    
    setCookie('PHPSESSID', getCookie('PHPSESSID'), 10);
});
JS;
    $this->inlineScript()->appendFile($this->basePath('js/utils.js'));
    $this->inlineScript()->captureEnd();    
    ?>
