<?php
$title = "Личный кабинет - " . $user->getLogin();
$this->headTitle($title);
$this->partial('/user/account/partial/script-and-style');
?>

<style>
.panel-body {
    min-height: 90px;
}
</style>

<!-- Page header -->
<div class="page-header">
    <div class="page-header-content">
        <div class="page-title">
            <h4><i class="fa fa-home position-left"></i> <?=$title?></h4>
            <div class="heading-elements">
                    <div class="heading-btn-group">                            
                    </div>
            </div>
        </div>
    </div>
</div>
<!-- /page header -->

<!-- Content area -->
<div class="content">
    <?=$this->infoTools()->renderInfoPlaceholder();?>
    <?=$this->DashboardLeftMenu()->renderPlaceholders()?>    
</div>
<!-- /Content area -->


