<?php
$this->headTitle('Сменить пароль');

//$this->mainMenu()->setActiveItemId('dropdown-menu');

$form->get('new_password')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Вседите новый пароль'
    ]);

$form->get('confirm_new_password')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Повторите новый пароль'
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();
?>

<h1>Смена пароля для <i><?= $this->escapeHtml($user->getLogin())?></i></h1>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
                
        <div class="form-group">
            <?= $this->formLabel($form->get('new_password')); ?>
            <?= $this->formElement($form->get('new_password')); ?>
            <?= $this->formElementErrors($form->get('new_password')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('confirm_new_password')); ?>
            <?= $this->formElement($form->get('confirm_new_password')); ?>
            <?= $this->formElementErrors($form->get('confirm_new_password')); ?>                  
        </div>
        
        <?= $this->formElement($form->get('csrf')); ?>
        
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   


