<?php
$this->headTitle('Редактирование учетной записи');

//$this->mainMenu()->setActiveItemId('dropdown-menu');

/*$this->pageBreadcrumbs()->setItems([
            'Начало'=>$this->url('home'),
            'Управление пользователями'=>$this->url('users'),
            'Редактирование учетной записи'=>$this->url('users', ['action'=>'edit', 'id'=>$user->getId()])
            ]);
*/
//$form->get('login')->setAttributes([
//    'class'=>'form-control disable', 
//    'placeholder'=>'Логин'
//    ]);

$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'name@example.com'
    ]);

$form->get('f')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Фамилия'
    ]);

$form->get('i')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Имя'
    ]);

$form->get('o')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Отчество'
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('submit')
        ->setAttributes(['class'=>'btn btn-primary'])
        ->setValue('Сохранить');

$form->prepare();
?>

<h1>Редактирование данных пользователя <?= $this->escapeHtml($user->getLogin()) ?></h1>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('f')); ?>
            <?= $this->formElement($form->get('f')); ?>
            <?= $this->formElementErrors($form->get('f')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('i')); ?>
            <?= $this->formElement($form->get('i')); ?>
            <?= $this->formElementErrors($form->get('i')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('o')); ?>
            <?= $this->formElement($form->get('o')); ?>
            <?= $this->formElementErrors($form->get('o')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>                  
        </div>
        
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   

