<?php
$title = "Список на модерацию";
$this->headTitle($title);
//$this->mainMenu()->setActiveItemId('adm_home');

function drawFilter($name)
{
    $result =<<<S
              <div class="input-group input-group-sm filter">
                  <input type="text" class="form-control form-control-sm filter-input" name="$name">
                  <span class="input-group-addon"><span class="glyphicon glyphicon-filter"></span></span>
              </div> 
S;
    return $result;
}
function drawFilterSelect($name, $valArr)
{
    $result =<<<S
              <div class="input-group input-group-sm filter">
                  <select class="form-control form-control-sm filter-input" name="$name">                
S;
    foreach($valArr as $key => $val) $result .= "<option value='$key'>$val</option>";
    $result .=<<<S
                </select>                      
              </div> 
S;
    return $result;
}
?>


<ul class="nav nav-tabs" id="myTab">
  <li><a href="/admin">Начало</a></li>
  <li class="active"><a href="#prv" data-toggle="tab">Учетные записи</a></li>
  <li><a href="#bus" data-toggle="tab">Транспорт</a></li>
</ul>

<p>
<?php if(!empty($successMessage)) : ?>
    <div class="alert alert-success alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <strong>Успешно!</strong> <?=$successMessage?>
    </div>   
<?php endif ?>

<?php if(!empty($errorMessage)) : ?>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <strong>Неудачно!</strong> <?=$errorMessage?>
    </div>
<?php endif ?>

<div class="tab-content">
    
  <div class="tab-pane active" id="prv">
        <div class="panel">
              <div class="panel-heading">
                <h3 class="panel-title">Данные учетных записей для проверки</h3>
              </div>
                <table class="table table-striped table-bordered">
                    <tr>
                        <th>Логин</th>
                        <th>Перевозчик</th>
                        <th>Данные для проверки</th>
                        <th>Статус</th>
                        <th>Действия</th>
                    </tr>
                    <tr>
                        <th><?=drawFilter("login")?></th>
                        <th><?=drawFilter("fio")?></th>
                        <th><?=drawFilter("title")?></th>
                        <th><?=drawFilterSelect("status", $arr_moderStatus)?></th>
                        <th>
                            <div class="input-group input-group-sm">
                                <button type="button" class="btn-xs btn-info" id="filter-clear" name="filter-clear">
                                    <span class="glyphicon glyphicon-remove"></span>
                                </button>
                            </div>
                        </th>
                    </tr>
                    
                    <tbody id="prv-moder-table-body">
                    <? if(sizeof($prv)==0) : ?>
                    <tr>
                        <td colspan="5">Список пуст</td>
                    </tr>    
                    <? endif; ?>
                    <? foreach($prv as $row) : ?>
                    <tr>
                        <td><?=$this->escapeHtml($row["login"])?></td>
                        <td><?=$this->escapeHtml($row["fio"])?></td>
                        <td><?=$this->escapeHtml($row["title"])?></td>
                        <td><?=$this->escapeHtml($arr_moderStatus[$row["status"]])?></td>
                        <td>
                            <button type="button" class="btn-xs btn-info" id="prv-moder-view-<?=$row["id_usr"]?>" name="prv-moder-view"><span class="glyphicon glyphicon-search"></span></button>
                            <button type="button" class="btn-xs btn-success" id="prv-moder-ok-<?=$row["id"]?>" name="prv-moder-ok"><span class="glyphicon glyphicon-ok"></span></button>
                            <button type="button" class="btn-xs btn-danger" id="prv-moder-fail-<?=$row["id"]?>" name="prv-moder-fail"><span class="glyphicon glyphicon-remove"></span></button>
                        </td>
                    </tr>    
                    <? endforeach; ?>
                    </tbody>    
                </table>
        </div>
  </div> <? // of prv?>
    
  <div class="tab-pane" id="bus">
      <h1>Требуется уточнение</h1>
  </div> <? // of bus?>

</div>








<script>
    function searchFilter(all)
    {
        var container = $("#prv-moder-table-body");
        container.hide(200);
        var inputs = $("div.filter").find(".filter-input");
        var data = {
            is_filter: true
        };
        if(all=="all") {
            data.all = true;
            $("div.filter").find(".filter-input").val("");
        }
        $.each(inputs, function(i, v){
            var index = $(v).attr("name");
            data[index] = $(v).val();
        })
        $.ajax({
                url: '/admin/moder',
                type: 'post',
                dataType: "json",
                data: data,
                success: function( data ) {
                    container.empty();
                    container.show(100);
                    $.each(data, function(i, v){
                        container.append($(v));
                        setCalbacks();
                    });
                } // success
            });//$.ajax        
    }
        
    function setCalbacks()
    {
        $("button[name='prv-moder-view']")
            .unbind("click")
            .on("click", function() {                
                var href = (window.location.protocol + "//" + window.location.host + "/admin/viewprv/"+$(this).attr("id").toString().replace(new RegExp("prv-moder-view-",'g'), ""));
                window.open(href);
        })
        $("button[name='prv-moder-fail']")
            .unbind("click")
            .on("click", function() {
            var self = this;    
            confirmMsg("Вы уверены?", function(){window.location.href = (window.location.protocol + "//" + window.location.host + "/moderation/fail/prv/"+$(self).attr("id").toString().replace(new RegExp("prv-moder-fail-",'g'), ""))});
        })
        $("button[name='prv-moder-ok']")
            .unbind("click")
            .on("click", function() {
            window.location.href = (window.location.protocol + "//" + window.location.host + "/moderation/ok/prv/"+$(this).attr("id").toString().replace(new RegExp("prv-moder-ok-",'g'), ""));
        })        
    }
</script>
    
<script>
  $(function () {
    setCalbacks();  
    $("div.filter input").on("keyup", function() {if($(this).val()!="") return searchFilter("");});
    $("div.filter select").val(2).on("change", function() {return searchFilter("");});
    $("#filter-clear").on("click", function() {return searchFilter("all");});
  })
</script>
