<?php
$this->headTitle('Учетные данные');

//$this->mainMenu()->setActiveItemId('dropdown-menu');
?>

<h2>Учетные данные</h2>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>Идентификатор:</th>
                <td><?= $this->escapeHtml($user->getId()) ?></th>
            </tr>
             <tr>
                <th>Логин:</th>
                <td><?= $this->escapeHtml($user->getLogin()) ?></th>
            </tr>
             <tr>
                <th>ФИО:</th>
                <td><?= $this->escapeHtml($user->getF() . " " . $user->getI() . " " .$user->getO()) ?></th>
            </tr>
            <tr>
                <th>E-mail:</th>
                <td><?= $this->escapeHtml($user->getEmail()) ?></th>
            </tr>
            <tr>
                <th>Дата регистрации:</th>
                <td><?= $this->escapeHtml($user->getDateCreatedAsString()) ?></th>
            </tr>
        </table>
    </div>
</div>