<?php
$this->headTitle('Информация о пользователе');

//$this->mainMenu()->setActiveItemId('dropdown-menu');

//$this->pageBreadcrumbs()->setItems([
//            'Начало'=>$this->url('home'),
//            'Управление пользователями'=>$this->url('users'),
//            'Просмотр учетной записи пользователя'=>$this->url('users', ['action'=>'view', 'id'=>$user->getId()])
//            ]);
?>

<h1>Информация о пользователе <i><?= $this->escapeHtml($user->getLogin())?></i></h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($user->getId()) ?></th>
            </tr>
             <tr>
                <th>Группа:</th>
                <td><?= $this->escapeHtml($user->getIdUsrType()->getName()) ?></th>
            </tr>
             <tr>
                <th>Логин:</th>
                <td><?= $this->escapeHtml($user->getLogin()) ?></th>
            </tr>
            <tr>
                <th>E-mail:</th>
                <td><?= $this->escapeHtml($user->getEmail()) ?></th>
            </tr>
            <tr>
                <th>Фамилия Имя Очество:</th>
                <td><?= $this->escapeHtml($user->getF()) ?> <?= $this->escapeHtml($user->getI()) ?> <?= $this->escapeHtml($user->getO()) ?></th>
            </tr>
            <tr>
                <th>Дата регистрации:</th>
                <td><?= $this->escapeHtml($user->getDateCreatedAsString()) ?></th>
            </tr>
            <tr>
                <th>Статус:</th>
                <td><?= $this->escapeHtml($user->getStatusAsString()) ?></th>
            </tr>
        </table>
    </div>
</div>