<?php
$title = "Персональные данные перевозчика";
$this->headTitle($title);
//$this->mainMenu()->setActiveItemId('admin_home');

function ShrtCheker($arr, $key) {
    if(empty($key)) return "";
    if(!is_array($arr)) return "";
    if(!isset($arr[$key])) return "";
    return $arr[$key];
}
?>

<ul class="nav nav-tabs" id="myTab">
  <li class="active"><a href="#view" data-toggle="tab"><?=$title?></a></li>
  <li><a href="#docs" data-toggle="tab">Сканы документов</a></li>
</ul>

<div class="page-header">
  <h1><?=$title?> <small><?= $this->escapeHtml($user->getLogin()) ?></small></h1>
  Зарегистрирован <?= $this->escapeHtml($user->getDateCreatedAsString("d.m.Yг.")) ?>
</div>

<div class="tab-content">
    
    <div class="tab-pane active" id="view">
       
        <div class="col-md-6">
        <div class="panel">
              <div class="panel-heading">
                <h3 class="panel-title">Информация пользователя</h3>
              </div>
                <table class="table table-striped table-bordered">
                    <tr>
                        <th>Группа:</th>
                        <td>
                            <?= $this->escapeHtml($user->getIdUsrType()->getName()) ?>
                            ( <?= $this->escapeHtml($user->getStatusAsString()) ?> )
                        </td>
                    </tr>                    
                     <tr>
                        <th>Логин:</th>
                        <td><?= $this->escapeHtml($user->getLogin()) ?></td>
                    </tr>
                    <tr>
                        <th>E-mail:</th>
                        <td><?= $this->escapeHtml($user->getEmail()) ?></td>
                    </tr>                    
                    <tr>
                        <th>ФИО:</th>
                        <td><?= $this->escapeHtml($user->getF() . " " . $user->getI() . " " . $user->getO()) ?></td>
                    </tr>                    
                    <tr>
                        <th>Кому подчинен:</th>
                        <td><?= $user->getIdOwner()?"Владелец":"Никому" ?></td>
                    </tr>                    
                </table>
        </div>
        </div>
        
<div class="col-md-6">
        <div class="panel">
              <div class="panel-heading">
                <h3 class="panel-title">Информация о фирме</h3>
              </div>
                <table class="table table-striped table-bordered">
                                            
                     <tbody>
                    <tr>
                        <th>Организационно-правовая форма:</th>
                        <td>
                        <?php 
                            switch($userData->getByName("opf")) { 
                                case 1: echo 'Юридическое лицо'; break;
                                case 2: echo 'Индивидуальный предприниматель'; break;
                            }
                        ?>
                        </td>
                    </tr>
                        
                     <tr>                         
                        <th>Наименование фирмы:</th>
                        <td><?= $this->escapeHtml($userData->getByName("title")) ?></td>
                    </tr>
                        
                     <tr>                         
                        <th>Должность руководителя:</th>
                        <td><?= $this->escapeHtml($userData->getByName("director")) ?></td>
                    </tr>
                        
                     <tr>                         
                        <th>ФИО руководителя:</th>
                        <td><?= $this->escapeHtml($userData->getByName("fio")) ?></td>
                    </tr>
                        
                     <tr>                         
                        <th>Действует на основании:</th>
                        <td><?= $this->escapeHtml($userData->getByName("osnova")) ?></td>
                    </tr>
                        
                     <tr>                         
                        <th>ИНН:</th>
                        <td><?= $this->escapeHtml($userData->getByName("inn")) ?></td>
                    </tr>
                        
                     <tr>                         
                        <th>КПП:</th>
                        <td><?= $this->escapeHtml($userData->getByName("kpp")) ?></td>
                    </tr>
                        
                     <tr>                         
                        <th>ОГРН:</th>
                        <td><?= $this->escapeHtml($userData->getByName("ogrn")) ?></td>
                    </tr>
                        
                </tbody></table>
        </div>
        </div>        
        
        <div class="col-md-6">
        <div class="panel">
              <div class="panel-heading">
                <h3 class="panel-title">Информация о лицензии</h3>
              </div>
                <table class="table table-striped table-bordered">
                                            
                     <tbody>
                        
                     <tr>                         
                        <th>Номер:</th>
                        <td><?= $this->escapeHtml($userData->getByName("lcensynum")) ?></td>
                    </tr>
                        
                     <tr>                         
                        <th>Действительна до:</th>
                        <td><?= $this->escapeHtml($userData->getByName("lcensydtend")) ?></td>
                    </tr>
                        
                     <tr>                         
                        <th>Международные перевозки:</th>
                        <td>
                        <?php 
                            switch($userData->getByName("international")) { 
                                case 1: echo 'Нет'; break;
                                case 2: echo 'Да'; break;
                            }
                        ?>
                        </td>
                    </tr>
                                                
                </tbody></table>
        </div>
        </div>        
        
        <div class="col-md-6">
        <div class="panel">
              <div class="panel-heading">
                <h3 class="panel-title">Платежные реквизиты</h3>
              </div>
                <table class="table table-striped table-bordered">
                                            
                     <tbody>
                        
                     <tr>                         
                        <th>Наименование банка:</th>
                        <td><?= $this->escapeHtml($userData->getByName("bankname")) ?></td>
                    </tr>
                        
                     <tr>                         
                        <th>БИК:</th>
                        <td><?= $this->escapeHtml($userData->getByName("bankbik")) ?></td>
                    </tr>
                        
                     <tr>                         
                        <th>Корреспондентский счет:</th>
                        <td><?= $this->escapeHtml($userData->getByName("bankks")) ?></td>
                    </tr>
                        
                     <tr>                         
                        <th>Расчетный счет:</th>
                        <td><?= $this->escapeHtml($userData->getByName("bankrs")) ?></td>
                    </tr>
                        
                                                
                </tbody></table>
        </div>
        </div>        
        
        <div class="col-md-6">
        <div class="panel">
              <div class="panel-heading">
                <h3 class="panel-title">Контактные данные</h3>
              </div>
                <table class="table table-striped table-bordered">
                                            
                     <tbody>
                        
                     <tr>                         
                        <th>Юридический адрес:</th>
                        <td><?= $this->escapeHtml($userData->getByName("uaddress")) ?></td>
                    </tr>
                        
                     <tr>                         
                        <th>Фактический адрес:</th>
                        <td><?= $this->escapeHtml($userData->getByName("faddress")) ?></td>
                    </tr>
                        
                     <tr>                         
                        <th>Контактный телефон:</th>
                        <td><?= $this->escapeHtml($userData->getByName("phone1")) ?></td>
                    </tr>
                        
                     <tr>                         
                        <th>Резервный телефон:</th>
                        <td><?= $this->escapeHtml($userData->getByName("phone2")) ?></td>
                    </tr>
                                                
                </tbody></table>
        </div>
        </div>        
        
        
    </div> <?/* id=view*/?>
    
    
  <div class="tab-pane" id="docs">
    <div class="row">
    <div class="col-md-12">
    <div class="panel">
          <div class="panel-heading">
            <h3 class="panel-title">Сканы документов перевозчика</h3>
          </div>
          <div class="panel-body">
              <div class="col-md-12">
                  <a href="/img/usr/regpaper/<?=$user->getId()?>" target="_blank" class="thumbnail"><img src="<?=$scanRegpaper?>" width="800"></a>                
              </div>  
              <div class="col-md-12">&nbsp;<hr></div>
              <div class="col-md-12">
                <a href="/img/usr/licensy/<?=$user->getId()?>" target="_blank" class="thumbnail"><img src="<?=$scanLicensy?>" width="800"></a>
              </div>    
          </div>
    </div>
    </div>      
    </div>      
</div>
    
    
</div>


<script>
  $(function () {
    $('#myTab a[href="#view"]').tab('show');        
  })
</script>
