<?php
$this->headTitle('Регистрация');
$this->publicMenu()->setActiveItemId('register');
$this->publicMenu()->setBreadCrumbs('home,register');

$this->headLink()
        ->appendStylesheet($this->basePath('css/front/register.css'.'?'.random_int(11111, 99999)))
    ;    


$form->get('email')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'name@example.com',
    'type'=>'email',
    ]);
$form->setAttribute('class', 'custom-form');

$form->get('submit')->setAttributes([
    'class'=>'custom-button center-block',
    'value'=>'Регистрация',
    'disabled' => 'disabled'
]);       
$form->prepare();
?>

<section class="terms">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
		<div class="form-container">

                    <!-- Main Heading Starts -->
                    <div class="text-center top-text">
                        <h1><span>регистрация</span> пользователя</h1>
                        <p>приятно видеть Вас среди наших клиентов!</p>
                    </div>
                    <!-- Main Heading Ends -->

                    <!-- Form Starts -->

                        <?php
                            if(!empty($errorMessage)):
                                ?>
                                <div class="col-sm-2"></div>
                                <div class="col-sm-8 text-center my_message visible">
                                    <div class="output_message error">
                                        <h4 class=head>Неудачно! </h4>
                                        <?=$errorMessage; ?>
                                    </div>
                                </div>
                                <div class="col-sm-2"></div>
                                <?php
                            endif;
                        ?>
                    
                        <?= $this->form()->openTag($form); ?>

                        <div class="row">
                        <div class="col-md-4">&nbsp;</div>
                        <div class="col-md-4">

                            <div class="form-group">
                                <?= $this->formLabel($form->get('idUsrType')); ?>
                                <?= $this->formElement($form->get('idUsrType')); ?>
                            </div>

                            <div class="form-group">
                                <?= $this->formLabel($form->get('f')); ?>
                                <?= $this->formElement($form->get('f')); ?>
                                <ul><li class="form-error-msg"><b><?= Application\Filter\LatToRus::get( $this->formElementErrors($form->get('f'))); ?></b></li></ul>
                            </div>

                            <div class="form-group">
                                <?= $this->formLabel($form->get('i')); ?>
                                <?= $this->formElement($form->get('i')); ?>
                                <ul><li class="form-error-msg"><b><?= Application\Filter\LatToRus::get( $this->formElementErrors($form->get('i'))); ?></b></li></ul>
                            </div>

                            <div class="form-group">
                                <?= $this->formLabel($form->get('o')); ?>
                                <?= $this->formElement($form->get('o')); ?>
                                <ul><li class="form-error-msg"><b><?= Application\Filter\LatToRus::get( $this->formElementErrors($form->get('o'))); ?></b></li></ul>
                            </div>

                            <div class="form-group">
                                <?= $this->formLabel($form->get('sex')); ?>
                                <?= $this->formElement($form->get('sex')); ?>
                            </div>

                            <div class="form-group">
                                <?= $this->formLabel($form->get('email')); ?>
                                <?= $this->formElement($form->get('email')); ?>
                                <ul><li class="form-error-msg"><b><?= Application\Filter\LatToRus::get( $this->formElementErrors($form->get('email'))); ?></b></li></ul>
                            </div>
                        </div>
                        <div class="col-md-4">&nbsp;</div>
                        </div>

                        <div class="row">
                        <div class="form-group col-md-12" id="iWill-text">
                            
                            <?= file_get_contents($_SERVER['DOCUMENT_ROOT'] . "/../doc_tpl/oferta-obrabotka-pd.html")?>

                        </div>
                        </div>
                    
                    <div class="row">
                    <div class="col-md-4">&nbsp;</div>
                    <div class="form-group col-md-8">                        
                        <div>
                                 <input type="checkbox" id="iWill-1">&nbsp;&nbsp;<label for="iWill-1">Я даю</label>
                                 &nbsp;<span class="read-iWill-text" data-oferta="oferta-obrabotka-pd">согласие на обработку моих персональных данных!</span>
                        </div>

                        <div>
                                 <input type="checkbox" id="iWill-2">&nbsp;&nbsp;<label for="iWill-2">Я принимаю условия</label>
                                 &nbsp;<span class="read-iWill-text" data-oferta="oferta-polzovatelskoe-soglashenie">пользовательского соглашения</span> &nbsp;и
                                 &nbsp;<span class="read-iWill-text" data-oferta="oferta-politika-konfidencialnosti">политики конфиденциальности</span>
                        </div>
                        
                    </div>                    
                    </div>
                                                    
                    <div class="row">
                    <div class="col-md-4">&nbsp;</div>
                    <div class="form-group col-md-4">
                        <div style="padding-left: calc( (100% - 300px) / 2 );">
                        <?= $this->formElement($form->get('captcha')); ?>
                        <ul><li class="form-error-msg"><b><?= Application\Filter\LatToRus::get( $this->formElementErrors($form->get('captcha'))); ?></b></li></ul>                        
                        </div>
                    </div>
                    <div class="col-md-4">&nbsp;</div>
                    </div>

                    <div class="row">
                    <div class="col-md-12">
                        <?= $this->formElement($form->get('submit')); ?>                    
                    </div>
                    </div>
                    
                    <?= $this->form()->closeTag(); ?>
                    <!-- Form Ends -->
                </div>
	    </div>
	</div>
    </div>
</section>

<div class="row" id="iWill-text" style="display:none;">
    <div class="oferta-obrabotka-pd">
        <?= file_get_contents($_SERVER['DOCUMENT_ROOT'] . "/../doc_tpl/oferta-obrabotka-pd.html")?>
    </div>
    <div class="oferta-polzovatelskoe-soglashenie">
        <?= file_get_contents($_SERVER['DOCUMENT_ROOT'] . "/../doc_tpl/oferta-polzovatelskoe-soglashenie.html")?>
    </div>
    <div class="oferta-politika-konfidencialnosti">
        <?= file_get_contents($_SERVER['DOCUMENT_ROOT'] . "/../doc_tpl/oferta-politika-konfidencialnosti.html")?>
    </div>
</div>


    <?php
    $this->inlineScript()->captureStart();
    echo <<<JS
$(function () {

  $("#iWill-text").hide();

  $("#iWill-1, #iWill-2").on("change", function(){
      var iWill = $("#iWill-1").prop("checked") && $("#iWill-2").prop("checked");
      $("#user-form").find(":submit").attr("disabled", iWill?null:"disabled");
  })

  $("span.read-iWill-text").unbind("click").bind("click", function(){            

        $("#oferta-dlg").remove();
        $(this).parent().after($("<div id=oferta-dlg />").html( $("#iWill-text div."+$(this).attr("data-oferta") ).html() ));
        $( "#oferta-dlg" ).dialog({
                modal: true,
                closeOnEscape: true,
                width: 1100,
                title: "Просмотр документа",
                dialogClass: "modal-window-dlg",
                buttons: {
                  Ok: function() {
                    $( this ).dialog( "close" );
                  }
                }
        });
        swing($(".modal-window-dlg"), 900, - parseInt($("header").css("height")) - 10);              
    });

    $("input[name='captcha[input]']").attr("placeholder", "Введите сюда буквы и цифры, которые Вы видите выше");    
    
    if(isMobile()){
        $("div.form-container").html(
            '<div class="col-sm-12 text-center my_message visible">'+
            '    <div class="output_message info left">'+
            '        <h4 class=head>Ограничение!</h4>'+
            '        Вы пытаетесь зарегистрироваться с мобильного устройства!<br><br>'+
            '        Система расчитана только для использования в десктопном режиме!<br><br>'+
            '        Для регистрации и работы войдите в систему при помощи ноутбука или персонального компьютера!'+
            '    </div>'+
            '</div>');
    };
    
});
JS;
    $this->inlineScript()->captureEnd();    
    ?>

