<?php
$this->headTitle('Сброс пароля');
$this->publicMenu()->setActiveItemId(false);
$this->publicMenu()->setBreadCrumbs('', 'Сброс пароля');

$this->headLink()
        ->appendStylesheet($this->basePath('css/front/reset-password.css'.'?'.random_int(11111, 99999)))
    ;    

$form->setAttribute('class', 'custom-form');

$form->get('email')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Email адрес',
    'required' => true,
    'autofocus' => false
    ]);

$form->get('submit')->setAttributes([
    'class'=>'custom-button center-block',
    'value'=>'Сбросить пароль'    
    ]);

$form->prepare();
?>

<section class="terms">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
		<div class="form-container">
                    <!-- Main Heading Starts -->
                    <div class="text-center top-text">
                        <h1><span>сброс</span> пароля</h1>
                        <p>C удовольствием выручим Вас!
                        <br>
                        Введите свой email адрес, с которым Вы регистрировались в системе и мы подскажем что делать дальше...</p>
                    </div>
                    <!-- Main Heading Ends -->
                    
        <?= $this->form()->openTag($form); ?>
        
                        <div class="row">
                        <div class="col-md-4">&nbsp;</div>
                        <div class="col-md-4">
                        <?= $this->formElement($form->get('email')); ?>
                        <ul><li class="form-error-msg"><b><?= Application\Filter\LatToRus::get( $this->formElementErrors($form->get('email'))); ?></b></li></ul>
                        <div class="col-md-4">&nbsp;</div>
                        </div>
                        </div>

                        <div class="row">
                        <div class="col-md-4">&nbsp;</div>
                        <div class="form-group col-md-4">
                            <div style="padding-left: calc( (100% - 300px) / 2 );">
                            <?= $this->formElement($form->get('captcha')); ?>
                            <ul><li class="form-error-msg"><b><?= Application\Filter\LatToRus::get( $this->formElementErrors($form->get('captcha'))); ?></b></li></ul>                        
                            </div>
                        </div>
                        <div class="col-md-4">&nbsp;</div>
                        </div>

                        <div class="row">
                        <div class="col-md-4">&nbsp;</div>
                        <div class="form-group col-md-4">
                            <?= $this->formElement($form->get('submit')); ?>
                            <?= $this->formElement($form->get('csrf')); ?>
                        </div>
                        <div class="col-md-4">&nbsp;</div>
                        </div>                            

        <?= $this->form()->closeTag(); ?>

                </div>
	    </div>
	</div>
    </div>
</section>
        