<?php
$this->headTitle('Смена пароля');
$this->publicMenu()->setActiveItemId(false);
$this->publicMenu()->setBreadCrumbs('', 'Смена пароля');

$this->headLink()
        ->appendStylesheet($this->basePath('css/front/set-password.css'.'?'.random_int(11111, 99999)))
    ;    

$form->setAttribute('class', 'custom-form');

$form->get('new_password')->setAttributes(array(
    'class'=>'form-control',
    'required' => true,
    'autofocus' => false,
    'placeholder'=>'Новый пароль'
    ));
$form->get('confirm_new_password')->setAttributes(array(
    'class'=>'form-control', 
    'required' => true,
    'autofocus' => false,
    'placeholder'=>'Подтвердите пароль'
    ));
$form->get('submit')->setAttributes(array(
    'class'=>'custom-button center-block',
    'value'=>'Изменить пароль'    
    ));

$form->prepare();
?>

<section class="terms">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
		<div class="form-container">
                    <!-- Main Heading Starts -->
                    <div class="text-center top-text">
                        <h1><span>смена</span> пароля</h1>
                        <p>Периодическая смена пароля - обязательна!!!
                        <br>
                        Введите новый пароль в форму, расположенную ниже...</p>
                    </div>
                    <!-- Main Heading Ends -->
                    
        <?= $this->form()->openTag($form); ?>


                        <div class="row">
                        <div class="col-md-4">&nbsp;</div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <?= $this->formLabel($form->get('new_password')); ?>
                                <?= $this->formElement($form->get('new_password')); ?>
                                <ul><li class="form-error-msg"><b><?= Application\Filter\LatToRus::get( $this->formElementErrors($form->get('new_password'))); ?></b></li></ul>
                            </div>
                        <div class="col-md-4">&nbsp;</div>
                        </div>
                        </div>
        
                        <div class="row">
                        <div class="col-md-4">&nbsp;</div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <?= $this->formLabel($form->get('confirm_new_password')); ?>
                                <?= $this->formElement($form->get('confirm_new_password')); ?>
                                <ul><li class="form-error-msg"><b><?= Application\Filter\LatToRus::get( $this->formElementErrors($form->get('confirm_new_password'))); ?></b></li></ul>
                            </div>    
                        <div class="col-md-4">&nbsp;</div>
                        </div>
                        </div>
            
                        <div class="row">
                        <div class="col-md-4">&nbsp;</div>
                        <div class="col-md-4">
                            <?= $this->formElement($form->get('submit')); ?>
                            <?= $this->formElement($form->get('csrf')); ?>
                        <div class="col-md-4">&nbsp;</div>
                        </div>
                        </div>

        <?= $this->form()->closeTag(); ?>
                    
                </div>
	    </div>
	</div>
    </div>
</section>
