
    <div class="panel">
          <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-ruble fa-1x"> </i> <?= $this->escapeHtml($title) ?></h3>
          </div>
          <div class="panel-body">                                          
        <table class="table">
            <tr>
                <td>
                    От <i class="fa fa-arrow-circle-o-down" aria-hidden="true"></i> 
                    - 
                    До <i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i>
                </td>
        <?php for($i=1; $i<sizeof($points); $i++){ ?>    
                <td class="center"><?=$points[$i]["data"][1]?>. <?=$points[$i]["data"][3]?>.</td>
        <?php } ?>    
            </tr>
            
        <?php foreach ($points as $key=>$p): ?>    
            <tr>
                <td><?=$p["data"][1]?>. <?=$p["data"][3]?>.</td>
            <?php 
                for($i=0; $i<$key; $i++)
                {
            ?>        
                <td class="center">x</td>                    
            <?php 
                }                
                for($i=$key+1; $i<sizeof($points); $i++)
                { 
                  $name = $p["data"][2]."-".$points[$i]["data"][2];  
            ?>                    
                <td  class="center"><?=(isset($costs[$name])?$costs[$name]:"-")?></td>
            <?php } ?>    
            </tr>
        <?php endforeach; ?>    
        </table>                            
  </div>
  </div>