<?php if(isset($options) && is_array($options))
{
    $option_name = isset($options["name"])?" name='{$options["name"]}'":"";
    $option_id = isset($options["id"])?" id='{$options["id"]}'":"";
    $option_class = isset($options["class"])?" class='{$options["class"]}'":" class='form-control form-control-sm filter-input'";
    $option_icon = isset($options["icon"])?" class='{$options["icon"]}'":" class='glyphicon glyphicon-filter'";
?>
    <div class="input-group input-group-sm filter">
        <input<?=$option_class?><?=$option_id?><?=$option_name?> type="text">
        <span class="input-group-addon"><span<?=$option_icon?>></span></span>
    </div> 
<?php           
}
?>
