<?php
    $ud = $user->getData();
//    var_dump($ud);
?>

<div class="row common">
    <div class="settings-block">
        <div class="panel">
            
            <div class="panel-heading">
                <h5 class="panel-title">Владелец учетной записи</h5>
            </div>
            
            <div class="panel-body">
              
                <div class="row">
                    <div class="col-md-5">
                        Фамилия *:
                    </div>
                    <div class="col-md-7">
                        <input class="form-control" name="f" value="<?=$this->escapeHtml($user->getF())?>" type="text">                              
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-5">
                        Имя *:
                    </div>
                    <div class="col-md-7">
                        <input class="form-control" name="i" value="<?=$this->escapeHtml($user->getI())?>" type="text">                              
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-5">
                        Отчество *:
                    </div>
                    <div class="col-md-7">
                        <input class="form-control" name="o" value="<?=$this->escapeHtml($user->getO())?>" type="text">                              
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                        Пол *:
                    </div>               
                    <div class="col-md-7">
                        <select name="sex" class="form-control">
                            <option value="1" <?=(($dvf->filter("profile.user.sex", $ud)=="1")?"selected":"")?>>Мужской</option>
                            <option value="0" <?=(($dvf->filter("profile.user.sex", $ud)=="0")?"selected":"")?>>Женский</option>
                        </select>
                    </div>               
                </div>               
                
                <div class="row">
                    <div class="col-md-5">
                        Дата рождения *:
                    </div>
                    <div class="col-md-7">
                        <input class="form-control" name="dr" value="<?=$this->escapeHtml($dvf->filter("profile.user.dr", $ud))?>" type="text">                              
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-md-5">
                        Гражданство *:
                    </div>
                    <div class="col-md-7">                        
                        <select class="form-control" name="grazhd" 
                                data-init-id="<?=$this->escapeHtml($dvf->filter("profile.user.grazhd", $ud))?>"
                                data-init-val="<?=$this->escapeHtml($dvf->filter("profile.user.grazhd_txt", $ud))?>"
                        ></select>                        
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-md-5">
                        Удостоверяющий документ *:
                    </div>
                    <div class="col-md-7">                        
                        <select class="form-control" name="passport_type" 
                                data-init-id="<?=$this->escapeHtml($dvf->filter("profile.user.passport_type", $ud))?>"
                                data-init-val="<?=$this->escapeHtml($dvf->filter("profile.user.passport_type_txt", $ud))?>"
                        ></select>                        
                    </div>
                </div>
                                
                <div class="row">
                    <div class="col-md-5">
                        Серия и номер *:
                    </div>
                    <div class="col-md-7">                        
                        <input class="form-control" name="passport" placeholder='Введите номер в соответствии с подсказкой' value="<?=$this->escapeHtml($dvf->filter("profile.user.passport", $ud))?>">
                        <div id="doc-num-example"></div>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-md-5">
                     E-mail *:
                    </div>
                    <div class="col-md-7">
                    <input class="form-control" name="email" placeholder="name@example.com" value="<?=$this->escapeHtml($user->getEmail())?>" type="text">                              
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12 center">
                        <input name="submitter" data-node="common" class="btn btn-primary" value="Сохранить" type="button">        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row contact">
    <div class="settings-block">
        <div class="panel">
              <div class="panel-heading">
                  <h5 class="panel-title">Контакты</h5>
              </div>
              <div class="panel-body">

                <div class="row">                
                    <div class="col-md-5">
                        Адрес проживания*:
                    </div>               
                    <div class="col-md-7">
                        <input name="faddress" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.contact.faddress", $ud))?>" type="text">                    
                    </div>               
                </div>               

                <div class="row">                               
                    <div class="col-md-5">
                        Телефон основной *:
                    </div>               
                    <div class="col-md-7">
                        <input name="phone1" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.contact.phone1", $ud))?>" maxlength="16" type="text">                    
                    </div>               
                </div>               

                <div class="row">                               
                    <div class="col-md-5">
                        Телефон резервный
                    </div>               
                    <div class="col-md-7">
                        <input name="phone2" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.contact.phone2", $ud))?>" maxlength="16" type="text">                    
                    </div>                
                </div>                

                <div class="row">
                    <div class="col-md-12 center">
                        <input name="submitter" data-node="contact" class="btn btn-primary" value="Сохранить" type="button">        
                    </div>
                </div>
                  
              </div>
        </div>
    </div>
</div>


<div class="row contact">
    <div class="settings-block">
        Поля, помеченные знаком <big> <b>*</b> </big> должны быть заполнены!
    </div>
</div>
