<?php
    $ud = $user->getData();
?>

<div class="row common">
    <div class="settings-block">
        <div class="panel">
            <div class="panel-heading">							
                <h5 class="panel-title">Владелец учетной записи</h5>
            </div>
                
            <div class="panel-body">
              
                <div class="row">
                    <div class="col-md-5">
                        Фамилия *:
                    </div>
                    <div class="col-md-7">
                        <input class="form-control" name="f" value="<?=$this->escapeHtml($user->getF())?>" type="text">                              
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-5">
                        Имя *:
                    </div>
                    <div class="col-md-7">
                        <input class="form-control" name="i" value="<?=$this->escapeHtml($user->getI())?>" type="text">                              
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-5">
                        Отчество *:
                    </div>
                    <div class="col-md-7">
                        <input class="form-control" name="o" value="<?=$this->escapeHtml($user->getO())?>" type="text">                              
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                     E-mail *:
                    </div>
                    <div class="col-md-7">
                    <input class="form-control" name="email" placeholder="name@example.com" value="<?=$this->escapeHtml($user->getEmail())?>" type="text">                              
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-md-12 center">
                        <input name="submitter" data-node="common" class="btn btn-primary" value="Сохранить" type="button">        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="row org">
    <div class="settings-block">
        <div class="panel">
              <div class="panel-heading">
                  <h5 class="panel-title">Организация / ИП</h5>
              </div>
              <div class="panel-body">

                <div class="row">
                    <div class="col-md-5">
                        Организационно правовая форма *:
                    </div>               
                    <div class="col-md-7">
                        <select name="opf" class="form-control">
                            <option value="1" <?=(($dvf->filter("profile.org.opf", $ud)==1)?"selected":"")?>>Юридическое лицо</option>
                            <option value="2" <?=(($dvf->filter("profile.org.opf", $ud)==2)?"selected":"")?>>Индивидуальный предприниматель</option>
                        </select>
                    </div>               
                </div>               

                <div class="row">                
                    <div class="col-md-5">
                        Полное наименование *:
                    </div>               
                    <div class="col-md-7">
                        <input name="title" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.org.title", $ud))?>" type="text">                    
                    </div>               
                </div>               

                <div class="row">                
                    <div class="col-md-5">
                        Сокращенное наименование *:
                    </div>               
                    <div class="col-md-7">
                        <input name="title_short" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.org.title_short", $ud))?>" type="text">                    
                    </div>               
                </div>               

                <div class="row view-only-firm">                               
                    <div class="col-md-5">
                        Должность руководителя *:
                    </div>               
                    <div class="col-md-7">
                        <input name="director" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.org.director", $ud))?>" type="text">                    
                    </div>               
                </div>               

                <div class="row">                    
                    <div class="col-md-5">
                       ФИО руководителя *:
                    </div>               
                    <div class="col-md-7">
                        <input name="fio" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.org.fio", $ud))?>" type="text">                    
                    </div>               
                </div>               

                <div class="row view-only-firm">
                    <div class="col-md-5">
                       Действует на основании *:
                    </div>               
                    <div class="col-md-7">
                        <input name="osnova" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.org.osnova", $ud))?>" type="text">                    
                    </div>               
                </div>               

                <div class="row">                               
                    <div class="col-md-5">
                       ИНН *:
                    </div>               
                    <div class="col-md-7">
                        <input name="inn" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.org.inn", $ud))?>" type="text">                    
                    </div>               
                </div>               

                <div class="row view-only-firm">
                    <div class="col-md-5">
                       КПП *:
                    </div>               
                    <div class="col-md-7">
                        <input name="kpp" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.org.kpp", $ud))?>" type="text">                    
                    </div>               
                </div>               

                <div class="row">                               
                    <div class="col-md-5">
                       ОГРН(ИП) *:
                    </div>               
                    <div class="col-md-7">
                        <input name="ogrn" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.org.ogrn", $ud))?>" type="text">                    
                    </div>               
                </div>               

                <div class="row">
                    <div class="col-md-12 center">
                        <input name="submitter" data-node="org" class="btn btn-primary" value="Сохранить" type="button">        
                    </div>
                </div>
              </div>
        </div>
    </div>
</div>

<div class="row operator">
    <div class="settings-block">
        <div class="panel">
              <div class="panel-heading">
                <h5 class="panel-title">Глобальные идентификаторы</h5>
              </div>
              <div class="panel-body">

                <div class="row">
                    <div class="col-md-5">
                        Идентификатор АЦБПДП:
                    </div>               
                    <div class="col-md-7">
                        <input name="acbpdp" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.operator.acbpdp", $ud))?>" type="text">                    
                    </div>               
                </div>               

                <div class="row">
                    <div class="col-md-12 center">
                        <input name="submitter" data-node="operator" class="btn btn-primary" value="Сохранить" type="button">        
                    </div>
                </div>
                  
              </div>
        </div>
    </div>
</div>

<div class="row rekvizit">
    <div class="settings-block">
        <div class="panel">
              <div class="panel-heading">
                  <h5 class="panel-title">Платежные реквизиты</h5>
              </div>
              <div class="panel-body">

                <div class="row">
                    <div class="col-md-5">
                        Наименование банка *:
                    </div>               
                    <div class="col-md-7">
                        <input name="bankname" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.rekvizit.bankname", $ud))?>" type="text">                    
                    </div>               
                </div>               

                <div class="row">
                    <div class="col-md-5">
                        БИК *:
                    </div>               
                    <div class="col-md-7">
                        <input name="bankbik" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.rekvizit.bankbik", $ud))?>" type="text">                    
                    </div>               
                </div>               

                <div class="row">
                    <div class="col-md-5">
                        Корреспондентский счет *:
                    </div>               
                    <div class="col-md-7">
                        <input name="bankks" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.rekvizit.bankks", $ud))?>" type="text">                    
                    </div>               
                </div>               

                <div class="row">
                    <div class="col-md-5">
                        Расчетный счет *:
                    </div>               
                    <div class="col-md-7">
                        <input name="bankrs" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.rekvizit.bankrs", $ud))?>" type="text">                    
                    </div>               
                </div>               

                <div class="row">
                    <div class="col-md-12 center">
                        <input name="submitter" data-node="rekvizit" class="btn btn-primary" value="Сохранить" type="button">        
                    </div>
                </div>
                  
              </div>
        </div>
    </div>
</div>



<div class="row contact">
    <div class="settings-block">
        <div class="panel">
              <div class="panel-heading">
                  <h5 class="panel-title">Контакты</h5>
              </div>
              <div class="panel-body">

                <div class="row">
                    <div class="col-md-5">
                        Юридический адрес *:
                    </div>               
                    <div class="col-md-7">
                        <input name="uaddress" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.contact.uaddress", $ud))?>" type="text">                    
                    </div>               
                </div>               

                <div class="row">                
                    <div class="col-md-5">
                        Фактический адрес *:
                    </div>               
                    <div class="col-md-7">
                        <input name="faddress" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.contact.faddress", $ud))?>" type="text">                    
                    </div>               
                </div>               

                <div class="row">                               
                    <div class="col-md-5">
                        Телефон основной *:
                    </div>               
                    <div class="col-md-7">
                        <input name="phone1" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.contact.phone1", $ud))?>" maxlength="16" type="text">                    
                    </div>               
                </div>               

                <div class="row">                               
                    <div class="col-md-5">
                        Телефон резервный:
                    </div>               
                    <div class="col-md-7">
                        <input name="phone2" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.contact.phone2", $ud))?>" maxlength="16" type="text">                    
                    </div>                
                </div>                

                <div class="row">
                    <div class="col-md-12 center">
                        <input name="submitter" data-node="contact" class="btn btn-primary" value="Сохранить" type="button">        
                    </div>
                </div>
                  
              </div>
        </div>
    </div>
</div>


<div class="row contact">
    <div class="settings-block">
        Поля, помеченные знаком <big> <b>*</b> </big> должны быть заполнены!
    </div>
</div>
