<?php
    $ud = $user->getData();
//    var_dump($ud);
?>

<div class="row common">
    <div class="settings-block">
        <div class="panel">

            <div class="panel-heading">
                <h5 class="panel-title">Владелец учетной записи</h5>
            </div>

            <div class="panel-body">

                <div class="row">
                    <div class="col-md-5">
                        Фамилия *:
                    </div>
                    <div class="col-md-7">
                        <input class="form-control" name="f" value="<?=$this->escapeHtml($user->getF())?>" type="text">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-5">
                        Имя *:
                    </div>
                    <div class="col-md-7">
                        <input class="form-control" name="i" value="<?=$this->escapeHtml($user->getI())?>" type="text">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-5">
                        Отчество *:
                    </div>
                    <div class="col-md-7">
                        <input class="form-control" name="o" value="<?=$this->escapeHtml($user->getO())?>" type="text">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                        Пол *:
                    </div>
                    <div class="col-md-7">
                        <select name="sex" class="form-control">
                            <option value="1" <?=(($dvf->filter("profile.user.sex", $ud)=="1")?"selected":"")?>>Мужской</option>
                            <option value="0" <?=(($dvf->filter("profile.user.sex", $ud)=="0")?"selected":"")?>>Женский</option>
                        </select>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                        Дата рождения *:
                    </div>
                    <div class="col-md-7">
                        <input class="form-control" name="dr" value="<?=$this->escapeHtml($dvf->filter("profile.user.dr", $ud))?>" type="text">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                        Удостоверяющий документ *:
                    </div>
                    <div class="col-md-7">
                        <select class="form-control" name="passport_type"
                                data-init-id="<?=$this->escapeHtml($dvf->filter("profile.user.passport_type", $ud))?>"
                                data-init-val="<?=$this->escapeHtml($dvf->filter("profile.user.passport_type_txt", $ud))?>"
                        ></select>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                        Серия и номер *:
                    </div>
                    <div class="col-md-7">
                        <input class="form-control" name="passport" placeholder='Введите номер в соответствии с подсказкой' value="<?=$this->escapeHtml($dvf->filter("profile.user.passport", $ud))?>">
                        <div id="doc-num-example"></div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                     E-mail *:
                    </div>
                    <div class="col-md-7">
                    <input class="form-control" name="email" placeholder="name@example.com" value="<?=$this->escapeHtml($user->getEmail())?>" type="text">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                        Документы:
                    </div>
                    <div class="col-md-7 right" data-scan-folder="Учетные данные" data-scan-tag="common">
                        <button name="docslist" class="btn btn-default"><span class="glyphicon glyphicon-briefcase"></span> Загруженные</button>
                        <button name="uploader" class="btn btn-default"><span class="glyphicon glyphicon-cloud-upload"></span> Загрузить</button>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12 center">
                        <input name="submitter" data-node="common" class="btn btn-primary" value="Сохранить" type="button">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="row org">
    <div class="settings-block">
        <div class="panel">
              <div class="panel-heading">
                <h5 class="panel-title">Организация / ИП</h5>
              </div>
              <div class="panel-body">

                <div class="row">
                    <div class="col-md-5">
                        Страна регистрации *:
                    </div>
                    <div class="col-md-7">
                        <select class="form-control" name="country"
                                data-init-id="<?=$this->escapeHtml($dvf->filter("profile.org.country", $ud))?>"
                                data-init-val="<?=$this->escapeHtml($dvf->filter("profile.org.country_txt", $ud))?>"
                        ></select>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                        Организационно правовая форма:
                    </div>
                    <div class="col-md-7">
                        <select name="opf" class="form-control">
                            <option value="1" <?=(($dvf->filter("profile.org.opf", $ud)==1)?"selected":"")?>>Юридическое лицо</option>
                            <option value="2" <?=(($dvf->filter("profile.org.opf", $ud)==2)?"selected":"")?>>Индивидуальный предприниматель</option>
                        </select>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                        Полное наименование *:
                    </div>
                    <div class="col-md-7">
                        <input name="title" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.org.title", $ud))?>" type="text">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                        Сокращенное наименование *:
                    </div>
                    <div class="col-md-7">
                        <input name="title_short" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.org.title_short", $ud))?>" type="text">
                    </div>
                </div>

                <div class="row view-only-firm">
                    <div class="col-md-5">
                        Должность руководителя *:
                    </div>
                    <div class="col-md-7">
                        <input name="director" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.org.director", $ud))?>" type="text">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                       ФИО руководителя *:
                    </div>
                    <div class="col-md-7">
                        <input name="fio" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.org.fio", $ud))?>" type="text">
                    </div>
                </div>

                <div class="row view-only-firm">
                    <div class="col-md-5">
                       Действует на основании *:
                    </div>
                    <div class="col-md-7">
                        <input name="osnova" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.org.osnova", $ud))?>" type="text">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                       ИНН *:
                    </div>
                    <div class="col-md-7">
                        <input name="inn" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.org.inn", $ud))?>" type="text">
                    </div>
                </div>

                <div class="row view-only-firm">
                    <div class="col-md-5">
                       КПП *:
                    </div>
                    <div class="col-md-7">
                        <input name="kpp" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.org.kpp", $ud))?>" type="text">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                       ОГРН(ИП) *:
                    </div>
                    <div class="col-md-7">
                        <input name="ogrn" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.org.ogrn", $ud))?>" type="text">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                        Документы:
                    </div>
                    <div class="col-md-7 right" data-scan-folder="Организация \ ИП" data-scan-tag="org">
                        <button name="docslist" class="btn btn-default"><span class="glyphicon glyphicon-briefcase"></span> Загруженные</button>
                        <button name="uploader" class="btn btn-default"><span class="glyphicon glyphicon-cloud-upload"></span> Загрузить</button>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12 center">
                        <input name="submitter" data-node="org" class="btn btn-primary" value="Сохранить" type="button">
                    </div>
                </div>
              </div>
        </div>
    </div>
</div>


<div class="row operator">
    <div class="settings-block">
        <div class="panel">
              <div class="panel-heading">
                <h5 class="panel-title">Глобальные идентификаторы</h5>
              </div>
              <div class="panel-body">

                <div class="row">
                    <div class="col-md-5">
                        Идентификатор АЦБПДП:
                    </div>
                    <div class="col-md-7">
                        <input name="acbpdp" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.operator.acbpdp", $ud))?>" type="text">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                        Документы:
                    </div>
                    <div class="col-md-7 right" data-scan-folder="Идентификация" data-scan-tag="operator">
                        <button name="docslist" class="btn btn-default"><span class="glyphicon glyphicon-briefcase"></span> Загруженные</button>
                        <button name="uploader" class="btn btn-default"><span class="glyphicon glyphicon-cloud-upload"></span> Загрузить</button>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12 center">
                        <input name="submitter" data-node="operator" class="btn btn-primary" value="Сохранить" type="button">
                    </div>
                </div>

              </div>
        </div>
    </div>
</div>



<div class="row licensy">
    <div class="settings-block">
        <div class="panel">
              <div class="panel-heading">
                  <h5 class="panel-title">Лицензии</h5>
              </div>
              <div class="panel-body">

                <div class="row">
                    <div class="col-md-5">
                        Номер лицензии *:
                    </div>
                    <div class="col-md-7">
                        <input name="lcensynum" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.licensy.lcensynum", $ud))?>" type="text" maxlength="50">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                        Бессрочная лицензия *:
                    </div>

                    <div class="col-md-7">
                        <input name="lcensypermanently" type="checkbox" <?=(filter_var($dvf->filter("profile.licensy.lcensypermanently", $ud), FILTER_VALIDATE_BOOLEAN)?"checked":"")?>>
                    </div>
                </div>


                <div class="row view-if-lcensypermanently">
                    <div class="col-md-5">
                        Действует до *:
                    </div>
                    <div class="col-md-7">
                        <input name="lcensydtend" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.licensy.lcensydtend", $ud))?>" type="text">
                    </div>
                </div>

                <div class="row">
                    &nbsp;
                </div>

                <div class="row">
                    <div class="col-md-5">
                       № удост. допуска к МП *:
                    </div>
                    <div class="col-md-7">
                        <input name="internationalnum" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.licensy.internationalnum", $ud))?>" type="text" maxlength="50">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                       Действует до *:
                    </div>
                    <div class="col-md-7">
                        <input name="internationaldtend" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.licensy.internationaldtend", $ud))?>" type="text">
                    </div>
                </div>

                <div class="row">
                    &nbsp;
                </div>

                <div class="row">
                    <div class="col-md-5">
                       № уведомления УГАДН *:
                    </div>
                    <div class="col-md-7">
                        <input name="ugadnnum" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.licensy.ugadnnum", $ud))?>" type="text" maxlength="50">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                       Действует до *:
                    </div>
                    <div class="col-md-7">
                        <input name="ugadndtend" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.licensy.ugadndtend", $ud))?>" type="text">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                        Документы:
                    </div>
                    <div class="col-md-7 right" data-scan-folder="Лицензии" data-scan-tag="licensy">
                        <button name="docslist" class="btn btn-default"><span class="glyphicon glyphicon-briefcase"></span> Загруженные</button>
                        <button name="uploader" class="btn btn-default"><span class="glyphicon glyphicon-cloud-upload"></span> Загрузить</button>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12 center">
                        <input name="submitter" data-node="licensy" class="btn btn-primary" value="Сохранить" type="button">
                    </div>
                </div>
              </div>
        </div>
    </div>
</div>

<div class="row strah">
    <div class="settings-block">
        <div class="panel">
              <div class="panel-heading">
                  <h5 class="panel-title">Страхующая организация</h5>
              </div>
              <div class="panel-body">

                <div class="row">
                    <div class="col-md-5">
                        Наименование:
                    </div>
                    <div class="col-md-7">
                        <input name="name" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.strah.name", $ud))?>" type="text">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                        Адрес:
                    </div>
                    <div class="col-md-7">
                        <input name="address" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.strah.address", $ud))?>" type="text">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                        Договор:
                    </div>
                    <div class="col-md-7">
                        <input name="dogovor" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.strah.dogovor", $ud))?>" type="text">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                        Дата начала действия:
                    </div>
                    <div class="col-md-7">
                        <input name="begin" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.strah.begin", $ud))?>" type="text">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                        Действует до:
                    </div>
                    <div class="col-md-7">
                        <input name="end" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.strah.end", $ud))?>" type="text">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                        Документы:
                    </div>
                    <div class="col-md-7 right" data-scan-folder="Страхование" data-scan-tag="strah">
                        <button name="docslist" class="btn btn-default"><span class="glyphicon glyphicon-briefcase"></span> Загруженные</button>
                        <button name="uploader" class="btn btn-default"><span class="glyphicon glyphicon-cloud-upload"></span> Загрузить</button>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12 center">
                        <input name="submitter" data-node="strah" class="btn btn-primary" value="Сохранить" type="button">
                    </div>
                </div>

              </div>
        </div>
    </div>
</div>


<div class="row rekvizit">
    <div class="settings-block">
        <div class="panel">
              <div class="panel-heading">
                  <h5 class="panel-title">Платежные реквизиты</h5>
              </div>
              <div class="panel-body">

                <div class="row">
                    <div class="col-md-5">
                        Наименование банка:
                    </div>
                    <div class="col-md-7">
                        <input name="bankname" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.rekvizit.bankname", $ud))?>" type="text">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                        БИК:
                    </div>
                    <div class="col-md-7">
                        <input name="bankbik" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.rekvizit.bankbik", $ud))?>" type="text">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                        Корреспондентский счет:
                    </div>
                    <div class="col-md-7">
                        <input name="bankks" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.rekvizit.bankks", $ud))?>" type="text">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                        Расчетный счет:
                    </div>
                    <div class="col-md-7">
                        <input name="bankrs" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.rekvizit.bankrs", $ud))?>" type="text">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                        Документы:
                    </div>
                    <div class="col-md-7 right" data-scan-folder="Банк" data-scan-tag="rekvizit">
                        <button name="docslist" class="btn btn-default"><span class="glyphicon glyphicon-briefcase"></span> Загруженные</button>
                        <button name="uploader" class="btn btn-default"><span class="glyphicon glyphicon-cloud-upload"></span> Загрузить</button>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12 center">
                        <input name="submitter" data-node="rekvizit" class="btn btn-primary" value="Сохранить" type="button">
                    </div>
                </div>

              </div>
        </div>
    </div>
</div>



<div class="row contact">
    <div class="settings-block">
        <div class="panel">
              <div class="panel-heading">
                  <h5 class="panel-title">Контакты</h5>
              </div>
              <div class="panel-body">

                <div class="row">
                    <div class="col-md-5">
                        Юридический адрес *:
                    </div>
                    <div class="col-md-7">
                        <input name="uaddress" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.contact.uaddress", $ud))?>" type="text">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                        Фактический адрес *:
                    </div>
                    <div class="col-md-7">
                        <input name="faddress" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.contact.faddress", $ud))?>" type="text">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                        Телефон основной *:
                    </div>
                    <div class="col-md-7">
                        <input name="phone1" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.contact.phone1", $ud))?>" maxlength="16" type="text">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                        Телефон резервный:
                    </div>
                    <div class="col-md-7">
                        <input name="phone2" class="form-control" value="<?=$this->escapeHtml($dvf->filter("profile.contact.phone2", $ud))?>" maxlength="16" type="text">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12 center">
                        <input name="submitter" data-node="contact" class="btn btn-primary" value="Сохранить" type="button">
                    </div>
                </div>

              </div>
        </div>
    </div>
</div>


<div class="row contact">
    <div class="settings-block">
        Поля, помеченные знаком <big> <b>*</b> </big> должны быть заполнены!
    </div>
</div>

