<?php
$title = "Покупка и бронирование билета на автобус";
$this->headTitle($title);
$this->publicMenu()->setActiveItemId('home');
$this->publicMenu()->setBreadCrumbs('', 'Бронирование и покупка билета');

    $this->inlineScript()
        ->appendFile($this->basePath( $this->basePath('js/front/pay.js'.'?'.random_int(11111, 99999)) ))
        ->appendFile($this->basePath('js/w/bus-view.js'.'?'.random_int(11111, 99999)))
        /*->appendFile($this->basePath('/js/jquery.mask.js'.'?'.random_int(11111, 99999)))*/
        ->appendFile($this->basePath('/js/phone-mask.js'.'?'.random_int(11111, 99999)))
        ->appendFile($this->basePath('/js/utils.js'.'?'.random_int(11111, 99999)))
        ;

    $this->headLink()
            ->appendStylesheet($this->basePath('css/w/bus-view-pub.css'.'?'.random_int(11111, 99999)))
            ->appendStylesheet($this->basePath('css/front/pay.css'.'?'.random_int(11111, 99999)))
        ;
?>

<?php
echo <<<JS
<script type="text/javascript">
    var id_reis='$id_reis';
    var provider='$provider_by_search';
    var reis_provider='$provider_by_reis';
    var curr_usr=false;
</script>
JS;

if(!empty($user))
echo <<<JS
<script type="text/javascript">
curr_usr={
    phone: '{$user['phone']}',
    email: '{$user['email']}',
    f: '{$user['f']}',
    i: '{$user['i']}',
    o: '{$user['o']}',
    sex: '{$user['sex']}',
    dr: '{$user['dr']}',
    grazhd: '{$user['grazhd']}',
    grazhd_txt: '{$user['grazhd_txt']}',
    doc: '{$user['doc']}',
    doc_txt: '{$user['doc_txt']}',
    doc_num: '{$user['doc_num']}',
    doc_mask: '{$user['doc_mask']}',
    doc_example: '{$user['doc_example']}',
};
</script>
JS;

?>

<section class="shop-checkout">
    <div class="container">
        <h3><?=$title?></h3>

        <div id="help" style="display: none;">
            <div class="button close"><i class="fa fa-angle-down"></i></div>

            <ol>
            <br>
            <h4>Как оформить билет?</h4>
            <br>
            <li>
            Перед оформлением внимательно ознакомьтесь с предоставленной информацией о поездке!<br>
            Остановки посадки и высадки в списке остановок выделены зеленым цветом.<br>
            Убедитесь, что дата, время, остановки посадки и высадки Вас устраивают и Вы готовы приобрести билеты.<br>
            </li>

            <li>
            Отметьте понравившиеся свободные места в автобусе. <br>
            Разметка мест:
            <span class="empty-place-color">Свободно</span>
            <span class="sold-place-color">Продано</span>
            <span class="reserved-place-color">Место забронировано</span>
            <span class="self-reserved-color">Зарезервировано Вами на 5 мин.</span>
            <span class="reserved-color">Зарезервировано за кем-то на 5 мин.</span>
            </li>

            <li>
            Укажите Ваши телефон и адрес электронной почты. <br>
            Телефон нужен для экстренной связи с Вами.<br>
            На электронную почту будет отправлено письмо для подтверждения заявки.<br>
            <b>Если Вы уже вошли в свою учетную запись, то эти значения введутся автоматически.</b>
            </li>

            <li>
            Введите информацию о пассажире. <br>
            Вы можете добавить или удалить пассажиров, нажимая кнопки <i class="fa fa-plus" style="color:green;"></i> и <i class="fa fa-close"  style="color:red;"></i>.<br>
            Если Вы уже вошли в свою учетную запись, то данные о первом пассажире введутся автоматически.
            </li>

            <li>
            Когда все будет готово, нажмите кнопку <span  style="color:green;">"Готово"</span>. <br>
            </li>

            <li>
            Проверьте свой почтовый ящик <span id="help-info-email" style="color:green;"></span> и ознакомьтесь с полученным от Гоубас письмом.<br>
            Там Вы найдете инструкции по подтверждению заказа, его оплате и прочим дальнейшим действиям.
            </li>

            <i class="fa fa-smile-o" aria-hidden="true"></i>&nbsp; Приятных покупок и спасибо, что Вы с нами!

            </ol>
        </div>

        <div class="row" id="form">
            <div class="col-xs-12">
                <table class="table search-result-table">
                    <tfoot>
                        <tr>
                            <th colspan="5">
                                <h4>Рейс не обнаружен!</h4>
                                <br>
                                <a href="/#pay" class="custom-button" style="width:200px;display:inline-block;"><span data-hover="Купить билет">Купить билет</span></a>
                            </th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>

        <div class="row" id="welcomina" style="display:none;">
            <div class="col-xs-12">
                <table class="table" style="background:none;">
                    <tfoot>
                        <tr>
                            <th>
                                <h4 class="center">Внимание! Вы должны произвести оплату в течение 30 минут!</h4>
                                <br>
                                <p>Неоплаченный заказ будет автоматически отменен через 30 минут!</p>
                                <p>Инструкции и ссылки для действий с заказом отправлены на адрес <span class="email"></span>!</p>

                                <p class="if-not-logged">Для упрощения процедуры повторной покупки билетов мы рекомендуем Вам пройти несложную регистрацию и настроить свою учетную запись.
                                    <br>
                                    После этого Ваши данные будут вводиться в оформляемые билеты автоматически!
                                    <br>
                                    Также Вы сможете отслеживать историю своих покупок и вести диалог с техподдержкой.
                                </p>

                                <p class="if-logged">Историю своих заказов Вы можете отслеживать в кабинете Гоубас!</p>
                                <p><i class="fa fa-smile-o" aria-hidden="true"></i>&nbsp; Спасибо Вам за то, что Вы используете Гоубас!</p>

                                <div class="center">
                                <a href="#" class="custom-button credit-card"><span data-hover="Оплатить...">Перейти к оплате ...</span></a>
                                </div>
                            </th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>

        <div class="row" id="iWill-text" style="display:none;">
            <div class="oferta-obrabotka-pd">
                <?= file_get_contents($_SERVER['DOCUMENT_ROOT'] . "/../doc_tpl/oferta-obrabotka-pd.html")?>
            </div>
            <div class="oferta-polzovatelskoe-soglashenie">
                <?= file_get_contents($_SERVER['DOCUMENT_ROOT'] . "/../doc_tpl/oferta-polzovatelskoe-soglashenie.html")?>
            </div>
            <div class="oferta-politika-konfidencialnosti">
                <?= file_get_contents($_SERVER['DOCUMENT_ROOT'] . "/../doc_tpl/oferta-politika-konfidencialnosti.html")?>
            </div>
        </div>


    </div>
</section>
