<?php
$title = "Онлайн-заказ № $order от $dt";
$this->headTitle($title);
$this->publicMenu()->setActiveItemId('home');
$this->publicMenu()->setBreadCrumbs('', 'Список билетов');

$this->inlineScript()
    ->appendFile($this->basePath( $this->basePath('js/front/ticket-token.js'.'?'.random_int(11111, 99999)) ))
    ->appendFile('https://3dsec.sberbank.ru/demopayment/docsite/assets/js/ipay.js')
    ;

$this->headLink()
        ->appendStylesheet($this->basePath('css/front/ticket-token.css'.'?'.random_int(11111, 99999)))
    ;
?>

<?php
if(!isset($date)) $date = ""; // хренов басфор!
echo <<<JS
<script type="text/javascript">
    var id_reis='$id_reis';
    var provider='$provider';
    var query='$query';
    var title='$title';
    var date='$date';
    var payed = $payed;
</script>
JS;
?>

<section class="shop-checkout">
    <div class="container">
        <h3>&nbsp;<?=$title?></h3>

        <div class="row" id="form">
            <div class="col-xs-12">
                <table class="table search-result-table">
                    <tfoot>
                        <tr>
                            <th>
                                <h4>В запрошенном списке нет билетов!</h4>
                            </th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>

    </div>
</section>
